version: '3.8'
services:
  next-app:
    build: ./ffit-1
    ports:
      - "3000:3000"
    volumes:
      - ./ffit-1:/usr/src/app
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rooot
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d 

    ports:
      - "3306:3306"
